import {test,expect,home,launch,action,pause,resume,clearGround,tap} from './helpers';
import {writeFile} from 'node:fs/promises';

test('a previous production cache upgrades to the identified build without losing paid queued orders',async({page,request})=>{
  test.setTimeout(100_000);
  test.skip(!process.env.FRONTIER_PREVIOUS_DIST || !!process.env.FRONTIER_TEST_URL,'Needs an isolated local host serving a saved previous dist via the test-only previous/release endpoints.');
  try {
    expect((await request.post('/__qa/previous')).ok()).toBe(true);
    await home(page);
    const oldRuntime=await page.locator('script[src]').first().getAttribute('src');
    await launch(page);await pause(page);
    await page.evaluate(async()=>{await navigator.serviceWorker.ready;});
    await expect.poll(()=>page.evaluate(()=>!!navigator.serviceWorker.controller)).toBe(true);
    const oldCaches=await page.evaluate(async()=>(await caches.keys()).filter(n=>n.startsWith('frontier-command-rts-game-')));
    await action(page,'panel-army').click();await page.getByRole('button',{name:'Queue 3 at a time',exact:true}).click();
    const fundsBefore=await page.evaluate(()=>window.__FRONTIER__.state.players[0].gold);
    await resume(page);
    await page.getByRole('button',{name:'Recruit Swordsman',exact:true}).click();
    await expect.poll(()=>page.evaluate(()=>window.__FRONTIER__.state.entities.filter(e=>e.team===0).flatMap(e=>e.queue).filter(q=>q.type==='unit'&&q.id==='swordsman'&&q.paidCost?.gold===45).length)).toBe(3);
    await pause(page);
    expect(await page.evaluate(()=>window.__FRONTIER__.state.players[0].gold)).toBeLessThan(fundsBefore-100);
    await action(page,'panel-build').click();await page.getByRole('button',{name:'Build House',exact:true}).click();
    await tap(page,await clearGround(page,'house'));await action(page,'confirm-placement').click();
    const snapshot=()=>page.evaluate(()=>{const f=window.__FRONTIER__,s=f.state;return{seed:s.settings.seed,time:s.time,paused:s.paused,gold:s.players[0].gold,wood:s.players[0].wood,population:s.players[0].population,production:s.entities.filter(e=>e.team===0&&e.kind==='building').map(e=>({id:e.id,type:e.type,queue:e.queue})),orders:s.pendingCommands,profile:f.profile};});
    const before=await snapshot();expect(before.orders.map(c=>c.type)).toContain('build');
    expect(before.production.flatMap(e=>e.queue).filter(q=>q.type==='unit'&&q.id==='swordsman')).toHaveLength(3);
    expect((await request.post('/__qa/release')).ok()).toBe(true);
    await page.evaluate(async()=>{await (await navigator.serviceWorker.getRegistration())!.update();});
    await expect(page.locator('#apply-update')).toBeVisible();
    await expect.poll(snapshot).toEqual(before);
    await Promise.all([page.waitForEvent('load'),page.locator('#apply-update').click()]);
    const identifier=page.locator('footer [data-build-id]');await expect(identifier).toBeVisible();
    const id=await identifier.getAttribute('data-build-id');expect(id).toMatch(/^fc-[0-9a-f]{12}$/);
    if(process.env.FRONTIER_EXPECT_BUILD_ID)expect(id).toBe(process.env.FRONTIER_EXPECT_BUILD_ID);
    const newRuntime=await page.locator('script[src]').first().getAttribute('src');
    expect(newRuntime).not.toBe(oldRuntime);
    await action(page,'continue').click();await expect.poll(()=>page.evaluate(()=>window.__FRONTIER__.playing)).toBe(true);
    await expect.poll(snapshot).toEqual(before);
    await expect(page.locator('#apply-update')).toHaveCount(0);
    await expect.poll(()=>page.evaluate(async()=>(await caches.keys()).filter(n=>n.startsWith('frontier-command-rts-game-')))).not.toEqual(oldCaches);
    const cachesNow=await page.evaluate(async()=>(await caches.keys()).filter(n=>n.startsWith('frontier-command-rts-game-')));
    expect(cachesNow).toHaveLength(1);expect(cachesNow.some(n=>oldCaches.includes(n))).toBe(false);
    await writeFile(test.info().outputPath('previous-cache-upgrade.json'),JSON.stringify({oldRuntime,newRuntime,buildId:id,oldCaches,cachesNow,before,after:await snapshot()},null,2));
    await page.screenshot({path:test.info().outputPath('previous-cache-queued-battle-resumed.png')});
    // Continue beyond restored equality: the same paid jobs and planned House
    // must execute exactly once through native Resume, not merely deserialize.
    const housePlan=before.orders.find(c=>c.type==='build');
    if(!housePlan||housePlan.type!=='build')throw new Error('Expected one paid-state House plan.');
    const workBefore=await page.evaluate(()=>{const s=window.__FRONTIER__.state;return{created:s.players[0].stats.unitsCreated,stats:{...s.players[0].stats},houses:s.entities.filter(e=>e.team===0&&e.type==='house').map(e=>e.id)};});
    const queueIds=before.production.flatMap(b=>b.queue).map(q=>q.queueId);
    expect(queueIds).toHaveLength(3);expect(new Set(queueIds).size).toBe(3);expect(queueIds.every(Boolean)).toBe(true);
    await resume(page);
    await expect.poll(()=>page.evaluate(({queueIds,plan})=>{const s=window.__FRONTIER__.state;return{paidJobsRemaining:s.entities.filter(e=>e.team===0).flatMap(e=>e.queue).filter(q=>queueIds.includes(q.queueId)).length,completedHouses:s.entities.filter(e=>e.team===0&&e.type==='house'&&e.x===plan.x&&e.y===plan.y&&e.buildProgress>=1).length};},{queueIds,plan:housePlan}),{timeout:50_000,intervals:[100]}).toEqual({paidJobsRemaining:0,completedHouses:1});
    await pause(page);
    const completed=await snapshot();
    const workAfter=await page.evaluate(()=>{const s=window.__FRONTIER__.state;return{created:s.players[0].stats.unitsCreated,stats:{...s.players[0].stats},houses:s.entities.filter(e=>e.team===0&&e.type==='house').map(e=>e.id)};});
    expect(workAfter.created-workBefore.created).toBe(3);
    expect(workAfter.houses).toHaveLength(workBefore.houses.length+1);
    expect(completed.orders).toEqual([]);
    expect(completed.gold-before.gold-(workAfter.stats.goldCollected-workBefore.stats.goldCollected)).toBeCloseTo(0,6);
    expect(completed.wood-before.wood-(workAfter.stats.woodCollected-workBefore.stats.woodCollected)).toBeCloseTo(-65,6);
    await action(page,'pause-menu').click();await action(page,'save-leave').click();
    await expect(action(page,'continue')).toBeVisible();await page.reload();await action(page,'continue').click();
    await expect.poll(()=>page.evaluate(()=>window.__FRONTIER__.playing)).toBe(true);
    await expect.poll(snapshot).toEqual(completed);
    const reloaded=await snapshot();
    await resume(page);await pause(page);
    expect(await page.evaluate(()=>window.__FRONTIER__.state.players[0].stats.unitsCreated)).toBe(workAfter.created);
    expect(await page.evaluate(()=>window.__FRONTIER__.state.entities.filter(e=>e.team===0&&e.type==='house').map(e=>e.id))).toEqual(workAfter.houses);
    await writeFile(test.info().outputPath('previous-cache-production-completed-once.json'),JSON.stringify({oldRuntime,newRuntime,buildId:id,housePlan,queueIds,before,workBefore,completed,workAfter,reloaded,afterRepeatedResume:await snapshot()},null,2));
    await page.screenshot({path:test.info().outputPath('previous-cache-production-completed-once.png')});
  } finally {await request.post('/__qa/release');}
});
