import {defineConfig, devices} from '@playwright/test';

/** Run against the production build: Vite dev deliberately does not register a worker. */
const external = process.env.FRONTIER_TEST_URL;
// Exact remaining identities from the cancelled full run 37745260925.
// The default/full gate remains available outside this isolated QA branch.
const continuation = !!process.env.CI && process.env.GITHUB_REF_NAME === 'qa-browser-check' && process.env.FRONTIER_FULL_BROWSER_QA !== '1';
const remainingTitles: Record<string, string[]> = {
  "phone-landscape": [
    "paused construction rejects an invalid site immediately and rejects overlap with a queued house",
    "landscape placement keeps the commander footprint on unobscured canvas",
    "native large-text guides expose objectives and retain their scrolling and dismissal controls",
    "ordinary field-guide close and expanded map have separate hit targets",
    "Rush Engineer abilities stay above expanded and collapsed command panels and receive clicks",
    "Rush status growth relocates controls without needing a resize or panel toggle",
    "income stays per game-second and four-digit stock HUD fits desktop, landscape, and a short phone",
    "recent building-damage UI fixture warns with tips off after 200s, freezes expiry, and View only focuses",
    "easy: focus loss freezes until explicit recovery without spending tactical pauses",
    "normal: focus loss freezes until explicit recovery without spending tactical pauses",
    "hard: focus loss freezes until explicit recovery without spending tactical pauses",
    "brutal: focus loss freezes until explicit recovery without spending tactical pauses",
    "mobile visibility recovery preserves the existing dialog and tactical queue",
    "desktop steering is released on interruption and cannot leak into recovery",
    "touch steering and pointer capture reset when the app is interrupted",
    "interruption silences audio until the explicit recovery gesture",
    "two authored campaign menus, live objectives and save/continue retain chapter identity",
    "chapter result fixture unlocks next mission once and persists record and cosmetic title",
    "chapter defeat retries original authored mission with a fresh stable match ID",
    "expedition keeps its own battle checkpoint when ordinary Continue is replaced",
    "branching expedition UI supports shop choices, reload, completion, defeat and fresh replay",
    "menu audio stays gesture gated and all six states are reachable",
    "saved distant Houses explain one extra neighbor, preserve both Houses, complete and reload",
    "native legal edge House warns before building and offers an explained new pair",
    "all eight peaceful lessons use real input, teach neighboring houses, and launch the named Outpost",
    "peaceful practice saves its real milestone and keeps the guide available after reload",
    "chapter objectives retain one DOM control across HUD ticks and native held clicks",
    "real chapter progress updates the pressed button label without replacing its node",
    "commander health updates retain focus and the native Focus commander control",
    "Rush status changes preserve the upgrade button even when the deck signature changes",
    "landscape placement keeps real touch targets and preview space at standard and larger text",
    "Credits/About is reachable, honest about provenance, keyboard dismissible and text-scalable",
    "Research shows construction dependencies, sequential levels and pending orders",
    "HUD disclosure targets meet 44px and announce current population / expanded state",
    "Faction legend explains three distinct material sets independently of team identity",
    "visual fixture: ironhold crest and material overlays",
    "visual fixture: wildborn crest and material overlays",
    "visual fixture: arcanists crest and material overlays",
    "native Keep distance gives a player ranged force the shared spacing behavior",
    "queued ranged stance saves exactly and includes future troops without changing currency",
    "ranged stance is visible at large text while native Move and Hold retain priority",
    "a previous production cache upgrades to the identified build without losing paid queued orders",
    "visible build identifier agrees in the menu and Credits and survives saved battle reload",
    "expanded Recruit queues leave every minimap quadrant clickable without changing the army selection",
    "rally wording identifies current producers and a later range retains its own destination",
    "a Keep-loss result uses the local perspective and a real retry starts cleanly",
    "the terminal chapter refresh displays completed objectives and final capacity before the saved result",
    "HUD updates after a result preserve practice progress and do not write tutorial preferences",
    "Rush setup can be cancelled and restarted, then real movement and waves work",
    "Rush upgrade offers survive dismissal and are claimed once through the UI",
    "Rush save, reload, and continue retain run state and presentation",
    "finished runs cannot be re-saved and counted twice; rematch starts a new run",
    "all four owned actor textures load from the scoped offline cache with unchanged progression",
    "a missing additional Spearman texture keeps the working set and supports a native retry",
    "a full profile store preserves a finished campaign, retries after reload, and rewards once",
    "blocked storage keeps the result open until a durable retry succeeds",
    "expedition Resume recovers a newer finished checkpoint after profile failure",
    "both owned actor textures load from the scoped offline cache with unchanged progression",
    "a missing additional Swordsman texture keeps the working set and supports a native retry",
    "native large-text messages clear existing objectives and guides without moving control hit targets",
    "christmas native Focus tap cancels targeting while clear canvas queues Move",
    "mythic native Focus tap cancels targeting while clear canvas queues Move",
    "dense troop counts include only visible on-screen living units and preserve native selection",
    "dense troop badges remain outside visible HUD controls through panel changes and rotation",
    "guide stage survives real save/reload/continue, stays readable while paused, and resets for a new battle",
    "christmas HUD pause leaves a native ground order available with expanded controls",
    "christmas native body selection and attack work through a faded foreground depot",
    "christmas a native tap on exposed enemy pixels beats a nearer friendly transparent rectangle",
    "mythic HUD pause leaves a native ground order available with expanded controls",
    "mythic native body selection and attack work through a faded foreground depot",
    "mythic a native tap on exposed enemy pixels beats a nearer friendly transparent rectangle",
    "christmas warlord native ground marker preserves selection and queues no movement",
    "christmas ranger native ground marker preserves selection and queues no movement",
    "christmas engineer native ground marker preserves selection and queues no movement",
    "mythic warlord native ground marker preserves selection and queues no movement",
    "mythic ranger native ground marker preserves selection and queues no movement",
    "mythic engineer native ground marker preserves selection and queues no movement",
    "native theme selection updates portraits and persists with unchanged progression",
    "artwork switching preserves paused battle, orders, selection and resources",
    "both complete sets and directional art work after offline reload at the production subpath",
    "a missing required directional image retains the working theme and reports recovery",
    "native commander movement uses several authored walk phases and reduced motion keeps heading",
    "workshop dimensions, named copies, test-return and reload preserve draft and history",
    "invalid workshop settings are atomic, Pan does not paint, and held brush is one undo",
    "complete skirmish preset, slots, preview and playback match the displayed setup"
  ],
  "pwa": [
    "production manifest, icons, worker and precache remain within repository scope",
    "after install, offline reload supports saved battle, new game, campaign, and editor",
    "an update waits for consent, saves the battle, then restarts safely",
    "an update waits for a finished result commit and reloads its command record once"
  ]
};
const escapeRegex = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
export default defineConfig({
  testDir: './tests/browser',
  timeout: 35_000,
  expect: {timeout: 8_000},
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: continuation ? 0 : process.env.CI ? 1 : 0,
  maxFailures: continuation ? 0 : process.env.CI ? 6 : 0,
  // Canvas-heavy games should not spawn one browser per reported host CPU.
  workers: process.env.FRONTIER_TEST_WORKERS ? Math.max(1, Number(process.env.FRONTIER_TEST_WORKERS)) : 2,
  reporter: [['list'], ['html', {open: 'never', outputFolder: 'playwright-report'}], ['json', {outputFile: 'playwright-report/remaining-89.json'}]],
  use: {
    baseURL: external || 'http://127.0.0.1:4181/rts-game/',
    trace: continuation ? 'off' : 'on-first-retry', screenshot: 'only-on-failure', video: 'off',
    launchOptions: process.env.PLAYWRIGHT_EXECUTABLE_PATH ? {executablePath: process.env.PLAYWRIGHT_EXECUTABLE_PATH} : {},
  },
  projects: [
    {name: 'desktop', use: {...devices['Desktop Chrome'], viewport: {width: 1440, height: 900}}, testIgnore: /pwa\.spec\.ts/},
    {name: 'phone-portrait', use: {...devices['Pixel 7'], viewport: {width: 390, height: 844}}, testIgnore: /pwa\.spec\.ts/},
    {name: 'phone-landscape', use: {...devices['Pixel 7'], viewport: {width: 844, height: 390}}, testIgnore: /pwa\.spec\.ts/},
    {name: 'pwa', use: {...devices['Desktop Chrome']}, testMatch: /pwa\.spec\.ts/},
  ].filter(project => !continuation || project.name in remainingTitles).map(project => continuation ? {...project, grep: new RegExp('(?:' + remainingTitles[project.name].map(escapeRegex).join('|') + ')$')} : project),
  webServer: external ? undefined : {
    command: 'npm run build && node tests/browser/serve-production.mjs',
    url: 'http://127.0.0.1:4181/rts-game/',
    reuseExistingServer: false, timeout: 120_000,
  },
});
