import { createHash } from 'node:crypto';
import { describe, it, expect } from 'vitest';
import { findPath, generateMap, DEFAULT_SETTINGS, type GameMap, type Point } from '../../src/sim';

// Golden paths were generated by the frozen pre-optimization Map/Set A* implementation.
// Exact waypoint ordering matters to legacy replays and deterministic combat outcomes.
const expectedHashes: Record<number, string> = {
    "16": "f506a25ad85aa21b6781321357bed78884d1837c823d679fa0cd8c87f900d1da",
    "32": "1ad4118810ecdfdb54f522a4916ea94555b5b179959cbec04e205c215b569402",
    "54": "4a8a083b5d2ce1551e6aaf79b1a77196d496669916738d4f9945895c7264882a",
    "120": "1368f9386480ded52c46ed7e01fd5120ee4aa0008d2b48bb357c0e7bbb451d50",
    "160": "188c50faf96b630e99d8249dd90f4396e2362106a158e967c774333d37d28de4"
};
const changedRoutes: Point[][] = [[{"x": 3.5, "y": 3.5}, {"x": 4.5, "y": 4.5}, {"x": 5.5, "y": 4.5}, {"x": 6.5, "y": 4.5}], [{"x": 3.5, "y": 2.5}, {"x": 4.5, "y": 2.5}, {"x": 5.5, "y": 2.5}, {"x": 6.5, "y": 3.5}, {"x": 6.5, "y": 4.5}], [{"x": 3.5, "y": 3.5}, {"x": 3.5, "y": 4.5}, {"x": 4.5, "y": 4.5}, {"x": 5.5, "y": 4.5}, {"x": 6.5, "y": 4.5}], [{"x": 3.5, "y": 3.5}, {"x": 4.5, "y": 4.5}, {"x": 5.5, "y": 4.5}, {"x": 6.5, "y": 4.5}]];

describe('pathfinding determinism', () => {
    it('preserves 900 legacy routes across map sizes, blocked goals and out-of-map starts', () => {
        let rng = 973218;
        const rand = () => { rng = (Math.imul(rng, 1664525) + 1013904223) >>> 0; return rng / 4294967296; };
        for (const width of [16, 32, 54, 120, 160]) {
            const hash = createHash('sha256');
            const map: GameMap = {
                ...generateMap({ ...DEFAULT_SETTINGS, mapSize: 'tiny', seed: 'PATH-FUZZ' }),
                width, height: width,
                tiles: Array.from({ length: width * width }, () => {
                    const n = rand();
                    return n < .08 ? 'rock' : n < .16 ? 'water' : n < .3 ? 'forest' : n < .4 ? 'marsh' : 'grass';
                }),
            };
            const blocked = new Set<number>();
            for (let n = 0; n < width * 2; n++) blocked.add(Math.floor(rand() * width * width));
            for (let n = 0; n < 180; n++) {
                const start = { x: rand() * width, y: rand() * width }, goal = { x: rand() * width, y: rand() * width };
                if (n % 12 === 0) goal.x = -1.5;
                if (n % 12 === 1) start.x = -.3;
                if (n % 12 === 2) goal.x = width + 2.4;
                if (n % 12 === 3) start.y = width + .3;
                if (n % 12 === 4) { goal.x = start.x; goal.y = start.y; }
                if (n % 5 === 0) map.tiles[Math.floor(rand() * width * width)] = 'water';
                if (n % 7 === 0) blocked.add(Math.floor(rand() * width * width));
                hash.update(JSON.stringify(findPath(map, start, goal, blocked)));
            }
            expect(hash.digest('hex'), `legacy route order for ${width} tiles`).toBe(expectedHashes[width]);
        }
    }, 15000);

    it('reads terrain and blocker changes immediately when reusing the same map', () => {
        const map: GameMap = { ...generateMap({ ...DEFAULT_SETTINGS, mapSize: 'tiny' }), width: 16, height: 16, tiles: Array(256).fill('grass') };
        const start = { x: 2.5, y: 2.5 }, goal = { x: 6.5, y: 4.5 }, blocked = new Set<number>();
        expect(findPath(map, start, goal, blocked)).toEqual(changedRoutes[0]);
        map.tiles[3 * 16 + 4] = 'water';
        expect(findPath(map, start, goal, blocked)).toEqual(changedRoutes[1]);
        blocked.add(2 * 16 + 5);
        expect(findPath(map, start, goal, blocked)).toEqual(changedRoutes[2]);
        map.tiles[3 * 16 + 4] = 'grass'; blocked.clear();
        expect(findPath(map, start, goal, blocked)).toEqual(changedRoutes[3]);
        expect(changedRoutes[2]).not.toEqual(changedRoutes[1]);
    });
});
