/** Original generative score. No network, sampled copyrighted music, or timing in the simulation. */
export class AudioDirector {
  private context:AudioContext|null=null; private master:GainNode|null=null; private musicGain:GainNode|null=null;
  private next=0;private beat=0;private active=false;private timer=0;private combat=0;private musicVolume=.32;private sfxVolume=.65;
  unlock(){if(!this.context){this.context=new AudioContext();this.master=this.context.createGain();this.master.connect(this.context.destination);this.musicGain=this.context.createGain();this.musicGain.connect(this.master);this.musicGain.gain.value=this.musicVolume*.18;}void this.context.resume();}
  setVolumes(music:number,sfx:number){this.musicVolume=music;this.sfxVolume=sfx;if(this.musicGain)this.musicGain.gain.setTargetAtTime(music*.18,this.context!.currentTime,.15);}
  start(){this.unlock();this.active=true;if(!this.timer)this.timer=window.setInterval(()=>this.schedule(),120);}
  stop(){this.active=false;}
  setCombat(value:number){this.combat=value;}
  private note(freq:number,duration:number,at:number,volume:number,wave:OscillatorType='sine',music=true){if(!this.context||!this.master)return;const osc=this.context.createOscillator(),gain=this.context.createGain();osc.type=wave;osc.frequency.value=freq;gain.gain.setValueAtTime(.0001,at);gain.gain.exponentialRampToValueAtTime(Math.max(.0001,volume),at+.035);gain.gain.exponentialRampToValueAtTime(.0001,at+duration);osc.connect(gain);gain.connect(music?this.musicGain!:this.master);osc.start(at);osc.stop(at+duration+.02);}
  private schedule(){if(!this.context||!this.active||this.context.state!=='running')return;const ctx=this.context;if(this.next<ctx.currentTime)this.next=ctx.currentTime+.04;while(this.next<ctx.currentTime+.35){const chord=[[146.83,220,293.66,349.23],[130.81,196,261.63,329.63],[174.61,261.63,349.23,440],[110,164.81,220,293.66]][Math.floor(this.beat/16)%4];if(this.beat%8===0){for(const f of chord)this.note(f,3.1,this.next,.13,'sine');this.note(chord[0]/2,2.3,this.next,.24,'triangle');}const order=[0,2,1,3,2,1,3,2];this.note(chord[order[this.beat%8]]*(this.beat%4===0?2:1),.8,this.next,.17,'sine');if(this.combat>.1){this.note(this.beat%2===0?58:87,.12,this.next,.13+this.combat*.1,'triangle');if(this.beat%4===0)this.note(chord[0]/2,.32,this.next,.16,'sawtooth');}this.beat++;this.next+=this.combat>.2?.29:.42;}}
  play(kind:'select'|'order'|'error'|'build'|'recruit'|'capture'|'ability'|'hit'|'victory'|'defeat'|'click'){if(!this.context||this.context.state!=='running')return;const at=this.context.currentTime,v=this.sfxVolume*.14;const table:Record<string,number[]>={select:[420],order:[330,440],error:[130,100],build:[220,330,440],recruit:[392,523],capture:[330,440,660],ability:[165,330,660],hit:[80],victory:[262,330,392,523,659],defeat:[220,196,164],click:[560]};for(const [i,f]of table[kind].entries())this.note(f,kind==='hit'?.08:.2,at+i*.085,v,kind==='hit'?'triangle':'sine',false);}
}
